/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ufu.poo2.si.telas.estoque;

import edu.ufu.poo2.si.control.ProdutoDAO;
import edu.ufu.poo2.si.model.Estoque;
import edu.ufu.poo2.si.model.Produto;
import edu.ufu.poo2.si.util.enums.EnumEstadoEstoque;
import edu.ufu.poo2.si.util.exceptions.ErroException;

import javax.swing.*;
import java.math.BigDecimal;

/**
 * @author gmahlow
 */
public class CadastroProduto extends javax.swing.JFrame {

    private Boolean editando;
    private Long codigoProdutoEditando;
    private Long codigoEstoqueEditando;

    private Produto produtoEditando;

    private ProdutoDAO produtoDAO;
    private DefaultComboBoxModel<EnumEstadoEstoque> estadoEstoqueList;

    private VisualizarProduto formBeforeOpenEdit;

    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        this.editando = false;
        this.estadoEstoqueList = new DefaultComboBoxModel<>();
        this.produtoDAO = new ProdutoDAO();
        preencheComboEstado();
        initComponents();
    }

    public void preencheComboEstado() {
        this.estadoEstoqueList.removeAllElements();
        this.estadoEstoqueList.addElement(EnumEstadoEstoque.EmEstoque);
        this.estadoEstoqueList.addElement(EnumEstadoEstoque.EmFalta);
        this.estadoEstoqueList.addElement(EnumEstadoEstoque.EmPreVenda);
    }

    public CadastroProduto(Boolean editando, VisualizarProduto formBeforeOpenEdit, Produto produtoEditando) {
        this();
        this.editando = editando;
        this.formBeforeOpenEdit = formBeforeOpenEdit;
        this.produtoEditando = produtoEditando;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSistema1 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        labelQtd = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        textQtdReserva = new javax.swing.JFormattedTextField();
        textQtd = new javax.swing.JFormattedTextField();
        labelQtdReserva = new javax.swing.JLabel();
        textPreco = new javax.swing.JFormattedTextField();
        labelPreco = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();

        labelSistema1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        labelSistema1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSistema1.setText("Sistema de Vendas");
        labelSistema1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setResizable(false);
        setLocationRelativeTo(null);

        labelNome.setText("Nome");

        comboEstado.setModel(estadoEstoqueList);

        labelQtd.setText("Quantidade");

        labelEstado.setText("Estado");

        textQtdReserva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        textQtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        labelQtdReserva.setText("Quantidade Reserva");

        textPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        labelPreco.setText("Preço");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelSistema1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                                .addGap(8, 8, 8))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(textNome)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(textQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(comboEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(labelNome)
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(labelQtd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(labelEstado)
                                                .addGap(77, 77, 77))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(textQtdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(textPreco)
                                                .addContainerGap())))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(labelQtdReserva)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelPreco)
                                .addGap(85, 85, 85))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelSistema1)
                                .addGap(13, 13, 13)
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelQtd)
                                        .addComponent(labelEstado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelQtdReserva)
                                        .addComponent(labelPreco))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textQtdReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (textQtd.getValue() == null || textNome.getText().isEmpty() || textQtdReserva.getValue() == null
                || textPreco.getValue() == null) {
            JOptionPane.showMessageDialog(null, "Você precisa preencher todos os campos corretamente!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nome = textNome.getText();
        Integer quantidade = Integer.valueOf(textQtd.getValue().toString());
        Integer quantidadeReservada = Integer.valueOf(textQtdReserva.getValue().toString());
        BigDecimal preco = new BigDecimal(textPreco.getValue().toString());
        EnumEstadoEstoque estado = (EnumEstadoEstoque) comboEstado.getSelectedItem();

        try {
            if (editando) {
                produtoEditando.setNomeProduto(nome);
                produtoEditando.setPreco(preco);
                produtoEditando.getEstoque().setEstadoEstoque(estado);
                produtoEditando.getEstoque().setQuantidade(quantidade);
                produtoEditando.getEstoque().setQuantidadeReservada(quantidadeReservada);

                produtoDAO.update(produtoEditando);
                formBeforeOpenEdit.preencheProdutosList();
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Produto atualizado!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            Estoque estoqueToBePersisted = new Estoque();
            estoqueToBePersisted.setQuantidadeReservada(quantidadeReservada);
            estoqueToBePersisted.setQuantidade(quantidade);
            estoqueToBePersisted.setEstadoEstoque(estado);

            Produto produtoToBePersisted = new Produto();
            produtoToBePersisted.setNomeProduto(nome);
            produtoToBePersisted.setEstoque(estoqueToBePersisted);
            produtoToBePersisted.setPreco(preco);

            produtoDAO.insert(produtoToBePersisted);

            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "Produto criado!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        } catch (ErroException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro desconhecido", "Erro!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<EnumEstadoEstoque> comboEstado;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelQtd;
    private javax.swing.JLabel labelQtdReserva;
    private javax.swing.JLabel labelSistema1;
    private javax.swing.JTextField textNome;
    private javax.swing.JFormattedTextField textPreco;
    private javax.swing.JFormattedTextField textQtd;
    private javax.swing.JFormattedTextField textQtdReserva;
    // End of variables declaration//GEN-END:variables

    public JFormattedTextField getTextQtdReserva() {
        return textQtdReserva;
    }

    public void setTextQtdReserva(JFormattedTextField textQtdReserva) {
        this.textQtdReserva = textQtdReserva;
    }

    public JFormattedTextField getTextQtd() {
        return textQtd;
    }

    public void setTextQtd(JFormattedTextField textQtd) {
        this.textQtd = textQtd;
    }

    public JFormattedTextField getTextPreco() {
        return textPreco;
    }

    public void setTextPreco(JFormattedTextField textPreco) {
        this.textPreco = textPreco;
    }

    public JTextField getTextNome() {
        return textNome;
    }

    public void setTextNome(JTextField textNome) {
        this.textNome = textNome;
    }

    public JComboBox<EnumEstadoEstoque> getComboEstado() {
        return comboEstado;
    }

    public void setComboEstado(JComboBox<EnumEstadoEstoque> comboEstado) {
        this.comboEstado = comboEstado;
    }

    public Long getCodigoEstoqueEditando() {
        return codigoEstoqueEditando;
    }

    public void setCodigoEstoqueEditando(Long codigoEstoqueEditando) {
        this.codigoEstoqueEditando = codigoEstoqueEditando;
    }

    public Long getCodigoProdutoEditando() {
        return codigoProdutoEditando;
    }

    public void setCodigoProdutoEditando(Long codigoProdutoEditando) {
        this.codigoProdutoEditando = codigoProdutoEditando;
    }
}
