/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ufu.poo2.si.telas.estoque;

import edu.ufu.poo2.si.control.ProdutoDAO;
import edu.ufu.poo2.si.model.Produto;
import edu.ufu.poo2.si.util.exceptions.ErroException;

import javax.swing.*;
import java.util.Collection;

/**
 * @author gmahlow
 */
public class VisualizarProduto extends javax.swing.JFrame {

    private ProdutoDAO produtoDAO;
    private DefaultListModel<Produto> produtosList;

    /**
     * Creates new form VisualizarProduto
     */
    public VisualizarProduto() throws ErroException {
        this.produtoDAO = new ProdutoDAO();
        this.produtosList = new DefaultListModel<>();
        preencheProdutosList();
        initComponents();
    }

    public void preencheProdutosList() throws ErroException {
        Collection<Produto> produtos = produtoDAO.buscarTodos();

        produtosList.removeAllElements();

        for (Produto produto : produtos)
            produtosList.addElement(produto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSistema1 = new javax.swing.JLabel();
        labelSistema2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProdutos = new javax.swing.JList<>();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        labelSistema1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        labelSistema1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSistema1.setText("Sistema de Vendas");
        labelSistema1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelSistema2.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        labelSistema2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSistema2.setText("Sistema de Vendas");
        labelSistema2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane1.setViewportView(listProdutos);
        listProdutos.setModel(produtosList);
        listProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelSistema2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelSistema2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnEditar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnRemover))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (listProdutos.getSelectedValue() == null)  {
            JOptionPane.showMessageDialog(null, "Selecione um produto!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Produto produtoSelected = listProdutos.getSelectedValue();

        CadastroProduto cadastroProduto = new CadastroProduto(true, this);
        cadastroProduto.setVisible(true);
        cadastroProduto.setCodigoEstoqueEditando(produtoSelected.getEstoque().getCodigoEstoque());
        cadastroProduto.setCodigoProdutoEditando(produtoSelected.getCodigoProduto());
        cadastroProduto.getComboEstado().setSelectedItem(produtoSelected.getEstoque());
        cadastroProduto.getTextNome().setText(produtoSelected.getNomeProduto());
        cadastroProduto.getTextPreco().setValue(produtoSelected.getPreco());
        cadastroProduto.getTextQtd().setValue(produtoSelected.getEstoque().getQuantidade());
        cadastroProduto.getTextQtdReserva().setValue(produtoSelected.getEstoque().getQuantidadeReservada());
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (listProdutos.getSelectedValue() == null)  {
            JOptionPane.showMessageDialog(null, "Selecione um produto!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Produto toBeRemoved = listProdutos.getSelectedValue();
        try {
            produtoDAO.delete(toBeRemoved.getCodigoProduto());
            preencheProdutosList();
            JOptionPane.showMessageDialog(null, "Produto deletado!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        } catch (ErroException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VisualizarProduto().setVisible(true);
                } catch (ErroException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelSistema1;
    private javax.swing.JLabel labelSistema2;
    private javax.swing.JList<Produto> listProdutos;
    // End of variables declaration//GEN-END:variables
}
