/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ufu.poo2.si.telas.menu;

import edu.ufu.poo2.si.telas.cadastro.CadastroCliente;
import edu.ufu.poo2.si.telas.visualizar.VisualizarCliente;

/**
 * @author gmahlow
 */
public class Principal extends javax.swing.JFrame {

	private static final long serialVersionUID = -1191136746816291528L;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCadastrarPedido;
	private javax.swing.JButton btnCadastrarProduto;
	private javax.swing.JButton btnCadastroCliente;
	private javax.swing.JButton btnVisualizarClientes;
	private javax.swing.JButton btnVisualizarEstoque;
	private javax.swing.JButton btnVisualizarPedido;
	private javax.swing.JLabel labelSistema;
	private javax.swing.JLabel labelSistema1;

	/**
	 * Creates new form Principal
	 */
	public Principal() {
		initComponents();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Principal().setVisible(true);
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		labelSistema = new javax.swing.JLabel();
		btnCadastroCliente = new javax.swing.JButton();
		btnVisualizarClientes = new javax.swing.JButton();
		labelSistema1 = new javax.swing.JLabel();
		btnCadastrarProduto = new javax.swing.JButton();
		btnVisualizarEstoque = new javax.swing.JButton();
		btnCadastrarPedido = new javax.swing.JButton();
		btnVisualizarPedido = new javax.swing.JButton();

		labelSistema.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
		labelSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelSistema.setText("Sistema de Vendas");
		labelSistema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		btnCadastroCliente.setText("Cadastrar Cliente");
		btnCadastroCliente.setActionCommand("Cadastrar Cliente");
		btnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCadastroClienteActionPerformed(evt);
			}
		});

		btnVisualizarClientes.setText("Visualizar Clientes");
		btnVisualizarClientes.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnVisualizarClientesActionPerformed(evt);
			}
		});

		labelSistema1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
		labelSistema1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelSistema1.setText("Sistema de Vendas");
		labelSistema1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		btnCadastrarProduto.setText("Cadastrar Produto");

		btnVisualizarEstoque.setText("Visualizar Estoque");

		btnCadastrarPedido.setText("Cadastrar Pedido");

		btnVisualizarPedido.setText("Visualizar Pedidos");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(labelSistema1, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup()
										.addComponent(btnCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 175,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(btnVisualizarClientes,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(btnCadastrarPedido,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
														.addComponent(btnCadastrarProduto,
																javax.swing.GroupLayout.PREFERRED_SIZE, 175,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(18, 18, 18)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(btnVisualizarEstoque,
														javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
												.addComponent(btnVisualizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
						.addContainerGap()));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(labelSistema1)
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(btnVisualizarClientes).addComponent(btnCadastroCliente))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(btnCadastrarProduto).addComponent(btnVisualizarEstoque,
												javax.swing.GroupLayout.Alignment.TRAILING))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(btnCadastrarPedido).addComponent(btnVisualizarPedido))
								.addContainerGap(19, Short.MAX_VALUE)));

		btnCadastroCliente.getAccessibleContext().setAccessibleName("btnCadastroCliente");

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnVisualizarClientesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnVisualizarClientesActionPerformed
		// TODO add your handling code here:
		new VisualizarCliente().setVisible(true);
	}// GEN-LAST:event_btnVisualizarClientesActionPerformed

	private void btnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCadastroClienteActionPerformed
		// TODO add your handling code here:
		new CadastroCliente().setVisible(true);
	}// GEN-LAST:event_btnCadastroClienteActionPerformed
		// End of variables declaration//GEN-END:variables
}
