/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ufu.poo2.si.telas.pedido;

import edu.ufu.poo2.si.Venda;
import edu.ufu.poo2.si.control.*;
import edu.ufu.poo2.si.model.*;
import edu.ufu.poo2.si.util.enums.EnumFormaPagamento;
import edu.ufu.poo2.si.util.exceptions.ErroException;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * @author gmahlow
 */
public class CadastroPedido extends javax.swing.JFrame {

    private Vendedor vendedorFromLogin;

    private Venda venda;

    private ClienteDAO clienteDAO;
    private VendedorDAO vendedorDAO;
    private ProdutoDAO produtoDAO;

    private DefaultComboBoxModel<EnumFormaPagamento> formaPagamentoList;
    private DefaultComboBoxModel<Cliente> clienteList;
    private DefaultComboBoxModel<Vendedor> vendedorList;
    private DefaultComboBoxModel<Produto> produtoList;
    private DefaultTableModel itemPedidoList;

    /**
     * Creates new form CadastroPedido
     */
    public CadastroPedido() throws ErroException {
        this.clienteDAO = new ClienteDAO();
        this.vendedorDAO = new VendedorDAO();
        this.produtoDAO = new ProdutoDAO();
        this.formaPagamentoList = new DefaultComboBoxModel<>();
        this.clienteList = new DefaultComboBoxModel<>();
        this.vendedorList = new DefaultComboBoxModel<>();
        this.produtoList = new DefaultComboBoxModel<>();
        this.itemPedidoList = new DefaultTableModel();
        this.venda = new Venda();
        preencheClienteList();
        preencheVendedorList();
        preencheFormaPagamentoList();
        preencheProdutoList();
        inicializaItemPedido();
        initComponents();
    }

    public CadastroPedido(Vendedor vendedorFromLogin) throws ErroException {
        this();
        this.vendedorFromLogin = vendedorFromLogin;
    }

    private void inicializaItemPedido() {
        itemPedidoList.addColumn("Produto");
        itemPedidoList.addColumn("Quantidade");
        itemPedidoList.addColumn("Valor Calculado");
        itemPedidoList.addColumn("Desconto");
    }

    private void preencheClienteList() throws ErroException {
        Collection<Cliente> clientes = clienteDAO.buscarTodos();

        clienteList.removeAllElements();

        for (Cliente cliente : clientes)
            clienteList.addElement(cliente);
    }

    private void preencheVendedorList() throws ErroException {
        Collection<Vendedor> vendedores = vendedorDAO.buscarTodos();

        vendedorList.removeAllElements();

        for (Vendedor vendedor : vendedores)
            vendedorList.addElement(vendedor);
    }

    private void preencheProdutoList() throws ErroException {
        Collection<Produto> produtos = produtoDAO.buscarTodos();

        produtoList.removeAllElements();

        for (Produto produto : produtos)
            produtoList.addElement(produto);
    }

    private void preencheFormaPagamentoList() throws ErroException {
        formaPagamentoList.removeAllElements();
        formaPagamentoList.addElement(EnumFormaPagamento.Boleto);
        formaPagamentoList.addElement(EnumFormaPagamento.Cartao);
        formaPagamentoList.addElement(EnumFormaPagamento.Dinheiro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSistema1 = new javax.swing.JLabel();
        comboCliente = new javax.swing.JComboBox<>();
        comboVendedor = new javax.swing.JComboBox<>();
        comboFormaPagamento = new javax.swing.JComboBox<>();
        labelCliente = new javax.swing.JLabel();
        labelVendedor = new javax.swing.JLabel();
        labelFormaPagamento = new javax.swing.JLabel();
        textValorTotal = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        comboProduto = new javax.swing.JComboBox<>();
        labelProduto = new javax.swing.JLabel();
        textQtd = new javax.swing.JFormattedTextField();
        labelQtd = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableItemPedido = new javax.swing.JTable();

        labelSistema1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        labelSistema1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSistema1.setText("Sistema de Vendas");
        labelSistema1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        comboCliente.setModel(clienteList);

        comboVendedor.setModel(vendedorList);

        comboFormaPagamento.setModel(formaPagamentoList);

        labelCliente.setText("Cliente");

        labelVendedor.setText("Vendedor");

        labelFormaPagamento.setText("Forma de Pagamento");

        textValorTotal.setEditable(false);

        jLabel1.setText("Valor Total");

        comboProduto.setModel(produtoList);

        labelProduto.setText("Produto");

        textQtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        labelQtd.setText("Quantidade");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAdd.setText("+");
        btnAdd.setToolTipText("");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("-");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        tableItemPedido.setModel(itemPedidoList);
        tableItemPedido.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableItemPedido.setDefaultEditor(Object.class, null);
        jScrollPane2.setViewportView(tableItemPedido);

        setResizable(false);
        setLocationRelativeTo(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(labelProduto)
                                                .addGap(123, 123, 123)
                                                .addComponent(labelQtd)
                                                .addContainerGap(531, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelSistema1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(47, 47, 47))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                                        .addComponent(comboProduto, javax.swing.GroupLayout.Alignment.LEADING, 0, 175, Short.MAX_VALUE)
                                                                                                        .addComponent(comboFormaPagamento, javax.swing.GroupLayout.Alignment.LEADING, 0, 175, Short.MAX_VALUE)
                                                                                                        .addComponent(comboCliente, javax.swing.GroupLayout.Alignment.LEADING, 0, 175, Short.MAX_VALUE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(comboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(textQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(textValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(6, 6, 6))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(22, 22, 22)
                                                                                                .addComponent(labelFormaPagamento)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                .addComponent(jLabel1)
                                                                                                .addGap(54, 54, 54)))
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(58, 58, 58)
                                                                                .addComponent(labelCliente)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(labelVendedor)
                                                                                .addGap(116, 116, 116)))
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelSistema1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelProduto)
                                        .addComponent(labelQtd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(comboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(textQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(labelVendedor)
                                                                        .addComponent(labelCliente)))
                                                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(comboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(labelFormaPagamento))
                                                                .addGap(10, 10, 10)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(textValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(comboFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(20, 20, 20)
                                .addComponent(btnSalvar)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (comboProduto.getSelectedItem() == null || comboCliente.getSelectedItem() == null ||
                comboVendedor.getSelectedItem() == null || comboFormaPagamento.getSelectedItem() == null ||
                textValorTotal.getValue() == null) {
            JOptionPane.showMessageDialog(null, "Você precisa preencher todos os campos corretamente!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Cliente cliente = (Cliente) comboCliente.getSelectedItem();
        Vendedor vendedor = (Vendedor) comboVendedor.getSelectedItem();
        EnumFormaPagamento formaPagamento = (EnumFormaPagamento) comboFormaPagamento.getSelectedItem();
        List<ItemPedido> itensPedido = getItemsPedido();
        BigDecimal valorTotal = new BigDecimal(textValorTotal.getValue().toString());

        if (itensPedido.size() == 0) {
            JOptionPane.showMessageDialog(null, "Você precisa inserir itens no pedido!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Pedido toBePersisted = new Pedido();
            toBePersisted.setItens(itensPedido);
            toBePersisted.setCliente(cliente);
            toBePersisted.setVendedor(vendedor);
            toBePersisted.setFormaPagamento(formaPagamento);
            toBePersisted.setValorTotal(valorTotal);

            venda.gravarPedido(toBePersisted);
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "Pedido criado!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        } catch (ErroException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro desconhecido", "Erro!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnSalvarActionPerformed

    public void insereItemTabela(ItemPedido itemPedido)  {
        itemPedidoList.addRow(new Object[]{itemPedido.getProduto(), itemPedido.getQuantidade(), itemPedido.getValor(), itemPedido.getDesconto()});
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (textQtd.getValue() == null) {
            JOptionPane.showMessageDialog(null, "Digite uma quantidade!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Produto produto = (Produto) comboProduto.getSelectedItem();
        Integer quantidade = Integer.parseInt(textQtd.getValue().toString());
        BigDecimal preco = produto.getPreco();

        ItemPedido itemPedido = new ItemPedido();
        itemPedido.setProduto(produto);
        itemPedido.setQuantidade(quantidade);
        itemPedido.setValor(preco);
        itemPedido.setNivelVendedoLibera(vendedorFromLogin.getNivel());
        venda.avaliaDescontoItemPedido(itemPedido);
        itemPedido.setValor(itemPedido.getValor().subtract(new BigDecimal(itemPedido.getDesconto())));

        insereItemTabela(itemPedido);

        textQtd.setValue(null);

        atualizaValorTotal();
    }//GEN-LAST:event_jButton1ActionPerformed

    private Pedido getPedidoTela() {
        Cliente cliente = (Cliente) comboCliente.getSelectedItem();
        Vendedor vendedor = (Vendedor) comboVendedor.getSelectedItem();
        EnumFormaPagamento formaPagamento = (EnumFormaPagamento) comboFormaPagamento.getSelectedItem();
        List<ItemPedido> itensPedido = getItemsPedido();

        Pedido pedidoTela = new Pedido();
        pedidoTela.setCliente(cliente);
        pedidoTela.setVendedor(vendedor);
        pedidoTela.setFormaPagamento(formaPagamento);
        pedidoTela.setItens(itensPedido);

        return pedidoTela;
    }

    private void atualizaValorTotal() {
        Integer qtdRows = tableItemPedido.getRowCount();
        BigDecimal valorTotal = BigDecimal.ZERO;

        for (int i = 0; i < qtdRows; i++) {
            BigDecimal valor = (BigDecimal) itemPedidoList.getValueAt(i, 2);
            Integer quantidade = (Integer) itemPedidoList.getValueAt(i, 1);
            Integer desconto = (Integer) itemPedidoList.getValueAt(i, 3);
            valor = valor.multiply(new BigDecimal(quantidade));
            valor = valor.subtract(new BigDecimal(desconto));

            valorTotal = valorTotal.add(valor);
        }

        textValorTotal.setValue(valorTotal);
    }

    private List<ItemPedido> getItemsPedido() {
        Integer qtdRows = tableItemPedido.getRowCount();
        List<ItemPedido> itensPedido = new ArrayList<>();

        for (int i = 0; i < qtdRows; i++) {
            Produto produto = (Produto) itemPedidoList.getValueAt(i, 0);
            Integer quantidade = (Integer) itemPedidoList.getValueAt(i, 1);
            BigDecimal valor = (BigDecimal) itemPedidoList.getValueAt(i, 2);
            Integer desconto = (Integer) itemPedidoList.getValueAt(i, 3);

            ItemPedido toBeAdded = new ItemPedido();
            toBeAdded.setQuantidade(quantidade);
            toBeAdded.setProduto(produto);
            toBeAdded.setValor(valor);
            toBeAdded.setDesconto(desconto);

            itensPedido.add(toBeAdded);

        }

        return itensPedido;
    }

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (tableItemPedido.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um item do pedido!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        itemPedidoList.removeRow(tableItemPedido.getSelectedRow());
        atualizaValorTotal();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroPedido().setVisible(true);
                } catch (ErroException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Cliente> comboCliente;
    private javax.swing.JComboBox<EnumFormaPagamento> comboFormaPagamento;
    private javax.swing.JComboBox<Produto> comboProduto;
    private javax.swing.JComboBox<Vendedor> comboVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelFormaPagamento;
    private javax.swing.JLabel labelProduto;
    private javax.swing.JLabel labelQtd;
    private javax.swing.JLabel labelSistema1;
    private javax.swing.JLabel labelVendedor;
    private javax.swing.JTable tableItemPedido;
    private javax.swing.JFormattedTextField textQtd;
    private javax.swing.JFormattedTextField textValorTotal;
    // End of variables declaration//GEN-END:variables


    public JFormattedTextField getTextValorTotal() {
        return textValorTotal;
    }

    public void setTextValorTotal(JFormattedTextField textValorTotal) {
        this.textValorTotal = textValorTotal;
    }

    public JFormattedTextField getTextQtd() {
        return textQtd;
    }

    public void setTextQtd(JFormattedTextField textQtd) {
        this.textQtd = textQtd;
    }

    public JTable getTableItemPedido() {
        return tableItemPedido;
    }

    public void setTableItemPedido(JTable tableItemPedido) {
        this.tableItemPedido = tableItemPedido;
    }

    public JComboBox<Vendedor> getComboVendedor() {
        return comboVendedor;
    }

    public void setComboVendedor(JComboBox<Vendedor> comboVendedor) {
        this.comboVendedor = comboVendedor;
    }

    public JComboBox<Produto> getComboProduto() {
        return comboProduto;
    }

    public void setComboProduto(JComboBox<Produto> comboProduto) {
        this.comboProduto = comboProduto;
    }

    public JComboBox<EnumFormaPagamento> getComboFormaPagamento() {
        return comboFormaPagamento;
    }

    public void setComboFormaPagamento(JComboBox<EnumFormaPagamento> comboFormaPagamento) {
        this.comboFormaPagamento = comboFormaPagamento;
    }

    public JComboBox<Cliente> getComboCliente() {
        return comboCliente;
    }

    public void setComboCliente(JComboBox<Cliente> comboCliente) {
        this.comboCliente = comboCliente;
    }

    public JButton getBtnAdd() {
        return btnAdd;
    }

    public void setBtnAdd(JButton btnAdd) {
        this.btnAdd = btnAdd;
    }

    public JButton getBtnRemove() {
        return btnRemove;
    }

    public void setBtnRemove(JButton btnRemove) {
        this.btnRemove = btnRemove;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public void setBtnSalvar(JButton btnSalvar) {
        this.btnSalvar = btnSalvar;
    }
}