/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ufu.poo2.si.telas.pedido;

import edu.ufu.poo2.si.control.PedidoDAO;
import edu.ufu.poo2.si.model.ItemPedido;
import edu.ufu.poo2.si.model.Pedido;
import edu.ufu.poo2.si.util.exceptions.ErroException;

import javax.swing.*;
import java.util.Collection;

/**
 *
 * @author gmahlow
 */
public class VisualizarPedido extends javax.swing.JFrame {

    private PedidoDAO pedidoDAO;
    private DefaultListModel<Pedido> pedidosList;

    /**
     * Creates new form VisualizarPedido
     */
    public VisualizarPedido() throws ErroException {
        this.pedidoDAO = new PedidoDAO();
        this.pedidosList = new DefaultListModel<>();
        initComponents();
        preencheListPedidos();
    }

    private void preencheListPedidos() throws ErroException {
        Collection<Pedido> pedidos = pedidoDAO.buscarTodos();

        pedidosList.removeAllElements();

        for (Pedido pedido : pedidos)
            pedidosList.addElement(pedido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listPedidos = new javax.swing.JList<>();
        btnVisualizar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        labelSistema2 = new javax.swing.JLabel();

        listPedidos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listPedidos.setModel(pedidosList);
        jScrollPane1.setViewportView(listPedidos);

        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnEditarActionPerformed(evt);
                } catch (ErroException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        labelSistema2.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        labelSistema2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSistema2.setText("Sistema de Vendas");
        labelSistema2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setResizable(false);
        setLocationRelativeTo(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSistema2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSistema2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemover))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencheTabelaItemPedido(Pedido pedido, CadastroPedido tela) {
        for (ItemPedido itemPedido : pedido.getItens())
            tela.insereItemTabela(itemPedido);
    }

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) throws ErroException {//GEN-FIRST:event_btnEditarActionPerformed
        if (listPedidos.getSelectedValue() == null)  {
            JOptionPane.showMessageDialog(null, "Selecione um pedido!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Pedido toBeEdited = listPedidos.getSelectedValue();

        CadastroPedido cadastroPedido = new CadastroPedido();
        cadastroPedido.setVisible(true);

        cadastroPedido.getComboCliente().setEnabled(false);
        cadastroPedido.getComboCliente().setSelectedItem(toBeEdited.getCliente());

        cadastroPedido.getComboFormaPagamento().setEnabled(false);
        cadastroPedido.getComboFormaPagamento().setSelectedItem(toBeEdited.getFormaPagamento());

        cadastroPedido.getComboProduto().setEnabled(false);

        cadastroPedido.getComboVendedor().setEnabled(false);
        cadastroPedido.getComboVendedor().setSelectedItem(toBeEdited.getVendedor());

        cadastroPedido.getTableItemPedido().setEnabled(false);
        preencheTabelaItemPedido(toBeEdited, cadastroPedido);

        cadastroPedido.getTextQtd().setEnabled(false);

        cadastroPedido.getTextValorTotal().setEnabled(false);
        cadastroPedido.getTextValorTotal().setValue(toBeEdited.getValorTotal());

        cadastroPedido.getBtnAdd().setEnabled(false);
        cadastroPedido.getBtnRemove().setEnabled(false);
        cadastroPedido.getBtnSalvar().setEnabled(false);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (listPedidos.getSelectedValue() == null)  {
            JOptionPane.showMessageDialog(null, "Selecione um pedido!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Pedido toBeRemoved = listPedidos.getSelectedValue();

        try {
            pedidoDAO.delete(toBeRemoved.getCodigoPedido());
            preencheListPedidos();
            JOptionPane.showMessageDialog(null, "Pedido deletado!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        } catch (ErroException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VisualizarPedido().setVisible(true);
                } catch (ErroException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelSistema2;
    private javax.swing.JList<Pedido> listPedidos;
    // End of variables declaration//GEN-END:variables
}
