/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ufu.poo2.si.telas.vendedor;

import edu.ufu.poo2.si.control.VendedorDAO;
import edu.ufu.poo2.si.model.Vendedor;
import edu.ufu.poo2.si.util.exceptions.ErroException;

import javax.swing.*;
import java.util.Collection;

/**
 *
 * @author gmahlow
 */
public class VisualizarVendedor extends javax.swing.JFrame {

    private VendedorDAO vendedorDAO;
    private DefaultListModel<Vendedor> vendedoresList;

    /**
     * Creates new form VisualizarVendedor
     */
    public VisualizarVendedor() throws ErroException {
        this.vendedorDAO = new VendedorDAO();
        this.vendedoresList = new DefaultListModel<>();
        preencheComponenteListVendedores();
        initComponents();
    }

    public void preencheComponenteListVendedores() throws ErroException {
        Collection<Vendedor> vendedores = vendedorDAO.buscarTodos();

        vendedoresList.clear();

        for (Vendedor vendedor : vendedores)
            this.vendedoresList.addElement(vendedor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSistema1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listVendedores = new javax.swing.JList<>();

        labelSistema1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        labelSistema1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSistema1.setText("Sistema de Vendas");
        labelSistema1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        listVendedores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listVendedores.setModel(vendedoresList);
        jScrollPane1.setViewportView(listVendedores);

        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSistema1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSistema1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemover))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (listVendedores.getSelectedValue() == null)  {
            JOptionPane.showMessageDialog(null, "Selecione um vendedor!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Vendedor toBeEdited = listVendedores.getSelectedValue();

        CadastroVendedor cadastroVendedor = new CadastroVendedor(true, this);
        cadastroVendedor.setVisible(true);
        cadastroVendedor.getTextNome().setText(toBeEdited.getNome());
        cadastroVendedor.getTextCpf().setText(toBeEdited.getCPF());
        cadastroVendedor.getComboNivel().setSelectedItem(toBeEdited.getNivel());
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (listVendedores.getSelectedValue() == null)  {
            JOptionPane.showMessageDialog(null, "Selecione um vendedor!", "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Vendedor toBeRemoved = listVendedores.getSelectedValue();
        try {
            vendedorDAO.delete(toBeRemoved.getCPF());
            preencheComponenteListVendedores();
            JOptionPane.showMessageDialog(null, "Vendedor deletado!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        } catch (ErroException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VisualizarVendedor().setVisible(true);
                } catch (ErroException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelSistema1;
    private javax.swing.JList<Vendedor> listVendedores;
    // End of variables declaration//GEN-END:variables
}
